# Generated by Django 4.0.5 on 2023-05-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=180)),
                ('registation_day', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(max_length=20)),
                ('registation_area', models.CharField(max_length=100)),
                ('uses', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=180)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=20)),
                ('indenty', models.CharField(max_length=20)),
                ('birthday', models.DateTimeField(auto_now=True)),
                ('accommodation', models.CharField(max_length=100)),
                ('place_of_birth', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistationCenterAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=180)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(default='admin', editable=False, max_length=10)),
                ('center_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistationDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=180)),
                ('start_day', models.DateTimeField(auto_now=True)),
                ('car_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resity_api.car')),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resity_api.registationcenteradmin')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resity_api.owner'),
        ),
    ]
